### ISSUE TITLE
Duda ubicación de archivos dentro del repositorio personal

### ISSUE THREAD

**Issue by IgorPeralta** [IIC2613-Inteligencia-Artificial-2023-1/Syllabus#10]
Hola!
Tengo una duda respecto a dónde tienen que ir los archivos, ¿ambos (.pdf de las preguntas 1 y 2 y el .lp de la pregunta 3) tienen que ir fuera de las carpetas del repositorio? o ¿el .lp tiene que estar dentro de la carpeta Visualizador?

De antemano muchas gracias!

**Comment by vicentevegaulloa** [comment]
Hola @IgorPeralta !

Cada archivo correspondiente a la respuesta de cada pregunta, debe ir en su carpeta respectiva. Esto quiere decir que El .pdf de la pregunta 1 debe ir en la carpeta "Reflexión y Teoría", los archivos correspondientes a la pregunta 2 deben estar en "DCCubos" y los archivos correspondientes a la pregunta 3 deben estar en "DCConnect".
