### ISSUE TITLE
Duda con ultima pregunta de la tarea

### ISSUE THREAD

**Issue by dalcalde5150** [IIC2613-Inteligencia-Artificial-2023-1/Syllabus#11]
Hola, 

El enunciado dice que nuestro programa "no debera incluir ninguna regla que
defina un puzle especifico", por lo que no entiendo como se supone que lo tenemos que programar sin definirle nisiquiera el tamaño del grid ni donde estan los pares de colores. Si pudieran guiarme un poco en como debe ser el desarrollo estaria muy agradecido.

Saludos.

**Comment by JRichi99** [comment]
Misma pregunta

**Comment by jpvergaralb** [comment]
misma duda, resolvemos nuestro programa asumiendo que recibiremos fila, columna y color de un input?

**Comment by jpvergaralb** [comment]
misma duda, resolvemos nuestro programa asumiendo que recibiremos fila, columna y color de un input?

**Comment by pabloalvarez67** [comment]
Misma duda

**Comment by Diegothx** [comment]
Misma pregunta aqui

**Comment by Bea2000** [comment]
Misma duda!

**Comment by vicentevegaulloa** [comment]
Hola a todos y todas,

Para trabajar en esta parte deben asumir que se les entregaran distintos valores de filas, columnas y colores. Para hacer que esto sea más facil de manejar quizás les ayude lo siguiente. En clingo se pueden llamar a dos o más programas en secuencia. Esto quiere decir que yo puedo ocupar un comando como este:

`clingo input.lp programa.lp`

y lo que ocurrirá es que clingo practimente concatenará ambos programas y los correrá como si fueran uno. De esta forma ustedes pueden separar su código y tener un `input.lp` donde si usen reglas que definan el puzzle y otro `.lp` sólo con la lógica.

Espero que haya quedado claro y si tienen más dudas pregunten nomás.

**Comment by JRichi99** [comment]
Cuando se habla de Xmax e Ymax, son constantes que tenemos que contemplar?
