### ISSUE TITLE
Tiempo de ejecución de DCCubos

### ISSUE THREAD

**Issue by IgorPeralta** [IIC2613-Inteligencia-Artificial-2023-1/Syllabus#12]
Hola, en la parte 2 de la pregunta de DCCubos, nos piden crear 20 escenarios distintos y ver el tiempo de ejecución para 1, 3 y 5 brazos, el problema es que con un brazo, 40 cubos y 1 brazo se vuelve realmente larga la ejecución del programa, ya que es exponencial.
En mí caso, que no tengo un computador malo, una ejecución con 20 instantes de tiempo me dice que es UNSATISFIABLE en 4.7s, mientras que si le doy 25 instantes se demora 18s, darle 1 instante adicional, es decir, 26 instantes, hace que se demore 46s, 27 y ya pasamos al minuto y 20 segundos. Nótese que con un brazo, mover de una configuración A a una configuración B, se demorará mucho más de 40 pasos para mover las 40 cajas, lo que si seguimos duplicando el tiempo, son como 7 días de ejecución, 20 veces eso y demás entrego la tarea para septiembre jajajaja.

¿Qué hacemos en este caso?

**Comment by IgorPeralta** [comment]
Hola @cafigueredo 

Creé un código Python para generar configuraciones aleatorias, dado que no hay especificaciones de cómo tienen que ser los problemas jajajaja. En mi caso en particular, me quedé pegado con 8 torres de inicio, de alturas variables, frente a 8 torres finales, con otras alturas variables.

**Comment by cafigueredo** [comment]
Te recomiendo no generar problemas de forma aleatoria ya que le podrías estar agregando mucha complejidad y por eso se demora más en encontrar una solucion. En su lugar, trabaja con problemas más sencillos donde la paralelizacion(uso de mas de una mano robotica) sea relevante, ya que lo que nos interesa es que las manos funcionen segun las reglas y que al aprovechar el funcionamiento paralelo se encuentre una solucion en menos pasos.

Piensa en problemas mas sencillos, como por ejemplo, 
Configuracion inicial: 5 torres con 8 bloques cada una
Configuracion final: Todos los bloques sobre la mesa

Este tipo de ejemplo debiese funcionar para 40 bloques sin mucho tiempo de ejecucion.

**Comment by Martinrsts** [comment]
Yo hice ese problema específicamente y con 5 brazos se demora poco, pero con 3 o 1 brazo se demora demasiado. Sé que es un ejemplo, pero si un problema tan simple como ese se demora tanto, ¿no va a ser muy difícil encontrar 20 problemas más simples que eso?

**Comment by BValdes16** [comment]
Tengo el mismo problema, especialmente con 1 un brazo. También estoy generando problemas aleatorios pero no debiese cambiar demasiado la dificultad, si al final son siempre unas 4 torres al inicio y otras 4 torres al final. Además, todo empeora considerando que para encontrar el mínimo de movimientos hay que correr cada problema quizás 8 veces. Con 20 bloques el problema corre en unos 20 segundos, ¿quizás podríamos hacer 20 bloques y comparar 1 vs 2 vs 3 brazos, en vez de 1 vs 3 vs 5?

**Comment by cafigueredo** [comment]
Hola @BValdes16 

Se cambio la cantidad de bloques a 20.

Recuerda que mientras más cercano el parametro bound al verdadero valor de minimo de turno, menos tiempo debiese tomar para correr el programa. Por eso es recomendable utilizar problemas en que el numero minimo de turnos es conocido a priori.
