### ISSUE TITLE
P2 Instante de tiempo en el que se logra el objetivo

### ISSUE THREAD

**Issue by Jairuru** [IIC2613-Inteligencia-Artificial-2023-1/Syllabus#13]
Hola buenas, 

Para el punto 2 de la pregunta 2, se nos pide que encontrar el instante de tiempo en que se llega al estado final para una configuración. Mi pregunta es, ¿Esto se hace a mano cambiando el bound? ¿O se hace derechamente con el comando minimize que nos piden aprender más abajo? Saludos.

**Comment by pabloalvarez67** [comment]
MIsma duda. Además, no me queda claro cual es la diferencia entre ambos gráficos que tenemos que realizar. Por ende, no me queda claro la diferencia entre: el tiempo de solución del programa VS el instante de tiempo en el que se logra el objetivo.

**Comment by pabloalvarez67** [comment]
> Hola @Jairuru, para encontrar el instante de tiempo en que se logra el objetivo debes ir cambiando el bound, tal como mencionaste. No es necesario usar el #minimize.
> 
> Hola @pabloalvarez67, la diferencia esta en lo que miden. El tiempo de solucion del programa se refiere a cuanto le toma al computador solucionar el problema, por ende está medido en segundos. El instante de tiempo en que se logra el objetivo se refiere al turno en que se resuelve el problema (se llega a la configuracion objetivo), por ende se mide en numero de turnos.

Comprendo, el tiempo de solución sería el tiempo en segundos que se tarda el programa en encontrar todos los modelos?

**Comment by cafigueredo** [comment]
@pabloalvarez67 

Para cada par (configuracion inicial, configuracion final) que tu programa resuelva, tienes que fijarte en el tiempo en que se demora en correr (s) y en cuantos turnos se resuelve. Para encontrar los turnos tienes que ir variando el parametro bound.

 Lo importante es que seas coherente, si usas como medida de tiempo el calculo de todos los modelos, debes usar la misma medida para todos los demas casos donde haya mas brazos.

**Comment by pabloalvarez67** [comment]
> @pabloalvarez67
> 
> Para cada par (configuracion inicial, configuracion final) que tu programa resuelva, tienes que fijarte en el tiempo en que se demora en correr (s) y en cuantos turnos se resuelve. Para encontrar los turnos tienes que ir variando el parametro bound.
> 
> Lo importante es que seas coherente, si usas como medida de tiempo el calculo de todos los modelos, debes usar la misma medida para todos los demas casos donde haya mas brazos.

Aún no me queda claro. Entiendo los turnos, pero no el tiempo. Que tiempo debo tabular y graficar por ejemplo acá:
Time: 3.908s (Solving: 0.19s 1st Model: 0.19s Unsat: 0.00s)

Gracias!

**Comment by cafigueredo** [comment]
@pabloalvarez67 

Utiliza el tiempo de 3.908s. Lo importante es que se note la diferencia al aprovechar el paralelismo cuando usas mas brazos.
