### ISSUE TITLE
Uso de #maximize{} en DCConnect y Problemas de visualizador con grillas rectangulares

### ISSUE THREAD

**Issue by mwoolvett** [IIC2613-Inteligencia-Artificial-2023-1/Syllabus#14]
Hola,

- ¿Se puede utilizar la función de #maximize{} en mi código? Si es así, en consola tengo que poner --quiet=1, para que se imprima solo el último resultado en consola y así haga sentido el Visualizador (ya que para este ocupan los datos que responde la consola). No se si esto último cree algún problema al corregir mi código de forma automática.

- ¿Debiera funcionar el visualizador con grillas rectangulares? Ya que al crear una con 4 filas y 5 columnas, me muestra una quinta fila en blanco. Me gustaría saber si es error mío o un problema del Visualizador.

Muchísimas gracias de antemano!
Matías

**Comment by Skablop** [comment]
Hola,

No hay problema en usar maximize, me parece que también puedes usar en consola "clingo 0 solucion.lp" para que te devuelva una única solución. De cualquier forma, puedes usar el readme de github para aclarar cualquier cosa que sea necesaria.

Sobre lo del visualizador, efectivamente crea por default una grilla cuadrada con el valor máximo entre la fila y la columna. ¿Además de hacer aparecer la fila en blanco genera algún comportamiento anormal? ¿O la solución se muestra correctamente?

Saludos.

**Comment by mwoolvett** [comment]
Además de hacer aparecer la fila en blanco, no genera ninngún comportamiento anormal, o sea la solución se muestra correctamente en las primeras 4 filas. 

Muchas gracias por la respuesta!
