### ISSUE TITLE
Tiempo pregunta 2

### ISSUE THREAD

**Issue by marcotroncoso** [IIC2613-Inteligencia-Artificial-2023-1/Syllabus#16]
Hola, con respecto al tiempo en la pregunta 2, es el tiempo en que me muestra todos los modelos que cumplen las condiciones? o basta con el tiempo en que muestra el primer modelo? Lo digo porque a veces hay que esperar harto para que te muestre los miles de modelos que se pueden hacer con los 40 bloques. Y tambien como comentan en la pregunta  [https://github.com/IIC2613-Inteligencia-Artificial-2023-1/Syllabus/issues/13#issue-1659590720](url) se demora muchisimo para un brazo mostrar la primera solución. Quedo atento a la respuesta de la pregunta del link.

**Comment by cafigueredo** [comment]
Hola @marcotroncoso 

Tienes que ser coherente con la medida de tiempo que eliges. Si eliges el tiempo para calcular todos los modelos, debes usarlo así en todos los problemas que ejecutes. Lo mismo ocurre si eliges el tiempo en calcular un solo modelo, debes utilizar la misma metrica en todos los problemas que ejecutes.
