### ISSUE TITLE
Problemas Código parser.py

### ISSUE THREAD

**Issue by amondinellir** [IIC2613-Inteligencia-Artificial-2023-1/Syllabus#17]
Hola. Tengo problemas al intentar ejecutar el código parser.py. Al parecer no es capaz de detectar el número máximo de filas y columnas. Más específicamente ocurre lo siguiente:

    grid_size = (max(x_values), max(y_values))
    ValueError: max() arg is an empty sequence

Y yo en mi código tengo definidas las filas y columnas como:

    fila (1..5).
    columna (1..5).

Y para ejecutar el código python escribo:

    clingo DCConnect.lp | python3 parser.py output.json

Espero que me puedan ayudar. Gracias.

**Comment by vicentevegaulloa** [comment]
Hola @amondinellir,

No será el espacio entre la a y el parentesis abierto? Si lo cambias por `fila(1..5)` y `columna(1..5)` podría funcionar. Avísame si te funciona así :)

**Comment by amondinellir** [comment]
Ahh perdón. Yo en mi código lo escribí sin esos espacios. Solo lo cambié aquí en la issue.

**Comment by KainaBGR** [comment]
Holaa, también me arroja ese error, intenté incluir el input en un archivo externo como el tip que nos diste y también lo intenté dentro del mismo archivo solucion.lp que estoy usando para configurar las reglas. Pero en ambos me sale este error :((

**Comment by Skablop** [comment]
Hola,

¿Podrías verificar el output solamente del archivo clingo (corriendo clingo DCConnect.lp) y verificar que los átomos fila(n) y columna(n) aparecen ahí? 

Es posible que quizá no estés mostrando esos átomos en la solución,  y en ese caso el parser tiraría ese error.

Saludos.

**Comment by amondinellir** [comment]
Ahh si ese era el problema. Muchas gracias por la ayuda!!

**Comment by KainaBGR** [comment]
También me sirvió correr los archivos de input y solución sin el parser y pude ver que el programa estaba unsatisfiable, entonces no habían átomos que pudiera utilizar, gracias :)
