### ISSUE TITLE
Problema con visualizador

### ISSUE THREAD

**Issue by jburdiles** [IIC2613-Inteligencia-Artificial-2023-1/Syllabus#18]
Holaa, tengo un problema con el visualizador en la pregunta 3, mi codigo tiene los caminos correctos (Hice varias pruebas dibujando los caminos jajask), pero al momento de usar el visualizador solo aparecen S's y E's (Las E's subrayadas) y no me muestra ningún camino entre las S's y las E's.

**Comment by Skablop** [comment]
Hola,

Podrías verificar si los átomos de los caminos aparecen en tu solución de la forma indicada en el enunciado, porque puede ser que haya alguna diferencia (quizá hay espacios demás o alguna diferencia en el orden de los argumentos).

Saludos.

**Comment by jburdiles** [comment]
Creo que esta correcto. aqui escribo un ejemplo de como tengo los colores, los limites de la grilla y el resultado que me da.

Grilla:

fila(1..5).
columna(1..5).

Colores:

color(azul, 2, 1).
color(azul, 1, 5).
color(rojo, 2, 2).
color(rojo, 5, 5).
color(verde, 3, 1).
color(verde, 3, 4).
color(gris, 5, 1).
color(gris, 5, 2).
color(morado, 5, 3).
color(morado, 5, 4).

Output:

[('morado', '5', '4', '5', '3'), ('gris', '5', '1', '5', '2'), ('verde', '3', '4', '4', '4'), ('rojo', '2', '2', '3', '2'), ('azul', '2', '1', '1', '1'), ('verde', '4', '1', '3', '1'), ('rojo', '4', '5', '5', '5'), ('verde', '4', '4', '4', '3'), ('azul', '1', '1', '1', '2'), ('rojo', '3', '2', '3', '3'), ('rojo', '2', '3', '2', '4'), ('azul', '1', '4', '1', '5'), ('rojo', '3', '3', '2', '3'), ('rojo', '3', '5', '4', '5'), ('verde', '4', '3', '4', '2'), ('verde', '4', '2', '4', '1'), ('rojo', '2', '4', '2', '5'), ('azul', '1', '3', '1', '4'), ('azul', '1', '2', '1', '3'), ('rojo', '2', '5', '3', '5')]

Los colores y la grilla estan tal cual en ese orden.

**Comment by jburdiles** [comment]
Creo que esta correcto. aqui escribo un ejemplo de como tengo los colores, los limites de la grilla y el resultado que me da.

Grilla:

fila(1..5).
columna(1..5).

Colores:

color(azul, 2, 1).
color(azul, 1, 5).
color(rojo, 2, 2).
color(rojo, 5, 5).
color(verde, 3, 1).
color(verde, 3, 4).
color(gris, 5, 1).
color(gris, 5, 2).
color(morado, 5, 3).
color(morado, 5, 4).

Output:

[('morado', '5', '4', '5', '3'), ('gris', '5', '1', '5', '2'), ('verde', '3', '4', '4', '4'), ('rojo', '2', '2', '3', '2'), ('azul', '2', '1', '1', '1'), ('verde', '4', '1', '3', '1'), ('rojo', '4', '5', '5', '5'), ('verde', '4', '4', '4', '3'), ('azul', '1', '1', '1', '2'), ('rojo', '3', '2', '3', '3'), ('rojo', '2', '3', '2', '4'), ('azul', '1', '4', '1', '5'), ('rojo', '3', '3', '2', '3'), ('rojo', '3', '5', '4', '5'), ('verde', '4', '3', '4', '2'), ('verde', '4', '2', '4', '1'), ('rojo', '2', '4', '2', '5'), ('azul', '1', '3', '1', '4'), ('azul', '1', '2', '1', '3'), ('rojo', '2', '5', '3', '5')]

Los colores y la grilla estan tal cual en ese orden.

**Comment by Skablop** [comment]
Ahh ahora entiendo. Es porque los colores los tienes escritos en español y para que funcionen deben estar en inglés  (para que el css esté correcto). Trata cambiando eso y me avisas.

**Comment by jburdiles** [comment]
Vaaalee, ahi si funcionaa, muchas graciaas :)
