### ISSUE TITLE
Syntax error en parser.py

### ISSUE THREAD

**Issue by stephenwpugh** [IIC2613-Inteligencia-Artificial-2023-1/Syllabus#19]
Hola! Al correr el código de la pregunta 3 con `clingo DCConnect.lp | python parser.py output.json` en un Mac M2 me arroja un SyntaxError que dice lo siguiente:
```SyntaxError: Non-ASCII character '\xc3' in file parser.py on line 71, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details```

Al abrir la página indicada, una de las posibles soluciones implica agregar una línea comentada en parser.py, y al probarlo "funciona" (me arroja el mismo error de la issue #17 , pero creo que es un avance).

La pregunta entonces es, debería modificar mi parser.py? o no alterarlo cuando lo suba al repositorio?

**Comment by Skablop** [comment]
Hola,

Si te sirve de esa forma utilizalo así nomás, pero no lo modifiques al momento de subirlo al repo.

De todas formas vamos a revisar el error para ver si es necesario modificarlo desde el repo base.

Saludos.

**Comment by stephenwpugh** [comment]
Muchas gracias por la respuesta!
