### ISSUE TITLE
Instalación de clingo en Mac

### ISSUE THREAD

**Issue by Krmn390** [IIC2613-Inteligencia-Artificial-2023-1/Syllabus#2]
¡Hola! Tengo un Mac, por lo que hay diferencias en la forma de instalación del tutorial que enviaron con lo que puedo hacer en mi Mac. ¿Me podrían ayudar?

**Comment by pabloalvarez67** [comment]
Yo hice brew install clingo en la terminal y listo. Debería funcionar para la mayoría de los Mac.

**Comment by BirdHusband** [comment]
Hola! Ojo que installar usando 'brew install clingo' siempre instalará la versión más reciente. Para instalar clingo 5.4.0 usen los siguientes comandos en la terminal:

1. `brew tap-new $USER/local-clingo`
2. `brew extract --version=5.4.0 clingo $USER/local-clingo`
3. `brew install clingo@5.4.0`

(si no tienen los Command Line Tools de XCode, se les pedirá instalarlos. Esto lo hacen con `xcode-select --install`.)

**Comment by BirdHusband** [comment]
Hola! Ojo que installar usando 'brew install clingo' siempre instalará la versión más reciente. Investigué y para instalar clingo 5.4.0 usen los siguientes comandos en la terminal:

`brew tap-new $USER/local-clingo`
`brew extract --version=5.4.0 clingo $USER/local-clingo`
`brew install clingo@5.4.0`
(si no tienen los Command Line Tools de XCode, se les pedirá instalarlos. Esto lo hacen con `xcode-select --install`).

**Comment by Krmn390** [comment]
La línea 2 del código me tira:
==> Searching repository history
Error: Could not find clingo! The formula or version may not have existed.
carmenpazseguelbetancur@200-67-148-eduroam-al ~ %

**Comment by BirdHusband** [comment]
@Krmn390 Pucha, ahí me pillaste. Tienes git instalado? (tap-new crea un pseudo repositorio que en realidad es local)

También puedes intentar con la solución que se muestra aquí: https://github.com/orgs/Homebrew/discussions/4326

**Comment by BirdHusband** [comment]
En el peor de los casos, dudo que haya mucho problema en simplemente instalar la versión más reciente. En la última clase, ví al profe usar clingo 5.6.0 en su Mac 😅

**Comment by Krmn390** [comment]
me quedo con loa última respuesta jeje. Muchas gracias por todo cabros!!
