### ISSUE TITLE
Duda enunciado Tarea 1 - Pregunta 2

### ISSUE THREAD

**Issue by Juancagp** [IIC2613-Inteligencia-Artificial-2023-1/Syllabus#20]
Hola, tengo duda con la siguiente parte de la pregunta 2 en la siguiente imagen: 
<img width="503" alt="image" src="https://user-images.githubusercontent.com/81201399/231924767-f467ccbc-1951-4917-bea4-f752219954ac.png">
a esto se refiere literalmente a que independiente de la cantidad de brazos, solo se podría sacar o poner un bloque en alguna torre una vez por turno?
por ejemplo: en el caso base del programa donde se comienza con una torre en aumento [mesa][a][b][c]. Aún si tuviera n brazos con n>1, sería imposible que en un solo turno sean sacados el cubo [c] y [b] y el cubo [a] puesto sobre [e] como se pide?

**Comment by Juancagp** [comment]
<img width="842" alt="image" src="https://user-images.githubusercontent.com/81201399/231938261-64cf2fa9-ee4b-496f-949a-e4d99e3ff890.png">
por ejemplo, puse como objetivo lo siguiente:
<img width="599" alt="image" src="https://user-images.githubusercontent.com/81201399/231938354-fa25eee7-fbc8-4f49-b1a0-27257f35863c.png">
con un máximo de movimientos por turno de igual a 3 y un bound= 3.
se puede notar que en el tiempo T=2, se puso [a] sobre [e] y además en el mismo tiempo se puso [b] sobre [a] y [c] sobre [b], lo cual iría en contra de lo que remarqué en lo anterior verdad?

**Comment by cafigueredo** [comment]
Hola @Juancagp

Estas en lo correcto, la situacion que describiste no puede ocurrir. Ya que si estas moviendo el bloque 'a' con una mano, no es posible que al mismo tiempo estes poniendo otro bloque sobre 'a'.

Si te fijas estas ubicando los bloque a y b sobre una misma torre al mismo tiempo. Como mencionaste, esto esta prohibido en el enunciado y por tanto no puede ocurrir.
