### ISSUE TITLE
Duda Pregunta 3

### ISSUE THREAD

**Issue by marcotroncoso** [IIC2613-Inteligencia-Artificial-2023-1/Syllabus#21]
Hola, tengo 2 dudas. La primera es si entendí bien que "camino(C,Yo,Xo,Yd,Xd)" es basicamente "moverse" a un cuadrado vecino?  y la otra es con como se "pinta" el tablero. Porque las posiciones iniciales se marcan con la letra S y las de llegada con E. Pero "camino(C,Yo,Xo,Yd,Xd)" debería ser lo que pinta el tablero? Porque puse unos valores a mano de "camino" para lograr conectar S con E, pero el tablero solo muestra S y E pero no el camino que recorre para juntarlos. Eso es normal? o en el tablero debería aparecer alguna letra que haga el recorrido?

**Comment by Skablop** [comment]
Hola,

Como dices efectivamente el predicado camino es para moverse a celdas vecinas.

Sobre el tema de la visualización, las celdas iniciales y finales no se definen a partir de del predicado camino (porque no hay cómo saber de dónde parte un camino), sino del predicado color. Si trataste de hardcodear los caminos y no te aparece nada puede deberse a que el string que se usa para el color debe estar escrito en inglés (para que el css funcione).

Saludos

**Comment by ExRage2000** [comment]
Entonces ¿Solo se necesita "color" para las casillas de inicio y fin? 
(Considerando que las intermedias usan "camino" para colorearse)

**Comment by Skablop** [comment]
Hola,

Sí, con eso deberia bastar para denotar las casillas de inicio y fin.

Saludos.
