### ISSUE TITLE
Detalles necesarios en informe de pregunta 2

### ISSUE THREAD

**Issue by MartinCastillo** [IIC2613-Inteligencia-Artificial-2023-1/Syllabus#22]
Hola, 
Me preguntaba sobre si en la pregunta 2 es necesario incluir explícitamente las condiciones iniciales y finales de los 20 problemas de las torres o si es suficiente detallar la información más general del problema como el número de torres antes y después, etc.

**Comment by cafigueredo** [comment]
Hola @MartinCastillo 

La idea es que en el informe quede bien claro el tipo de problema que estas resolviendo. Si te complica el espacio que pueda ocupar en el informe, te recomiendo que dejes los 20 problemas en un anexo al final del informe.

Lo importante es que se puedan reproducir los problemas en caso que ocurra alguna discrepancia.
