### ISSUE TITLE
Pregunta 3. Camino caso pous adyacentes

### ISSUE THREAD

**Issue by Martinrsts** [IIC2613-Inteligencia-Artificial-2023-1/Syllabus#24]
¿Para el problema a solucionar puede haber una conexión entre dos colores de un solo camino? Por ejemplo, si tenemos el caso que existe color(C,1,1) y color(C,1,2), ¿puede ser camino(C,1,1,1,2) el único camino de color C?

**Comment by psotogomez** [comment]
Hola! la respuesta es no, debe existir un camino que sea distinto a solamente los dos pous, a pesar que estos sean adjacentes.

**Comment by IgnAMS** [comment]
Hola! Por que no se podria hacer un camino de dos pous? No recuerdo haber visto algo en el enunciado que no lo permitiese. 

Saludos!

**Comment by psotogomez** [comment]
Hola! En el enunciado dice que "El objetivo es encontrar **un camino entre cada par de celdas** del mismo color de forma tal que los caminos no se crucen (compartan celdas)." Un ejemplo de esto es: 
<img width="324" alt="image" src="https://user-images.githubusercontent.com/125215250/232848986-3e847679-7356-46fa-8402-2bba44dcb4f5.png">
