### ISSUE TITLE
Duda pregunta 3: celdas vecinas

### ISSUE THREAD

**Issue by 0wulf** [IIC2613-Inteligencia-Artificial-2023-1/Syllabus#25]
Hola, el enunciado de la pregunta 3 esppecifica lo siguiente
![image](https://user-images.githubusercontent.com/101217121/232346835-4d856a9d-97c5-4d0e-9f44-ac8baf3cb725.png)

Mi duda es la siguiente: como se define celda vecina? son celdas aydacentes o cualquiera de la grilla, o las celdas del perímetro?
Gracias de antemano.

**Comment by psotogomez** [comment]
Hola! Una celda vecina es equivalente a una celda adyacente. (recordar que estas no son diagonales)
