### ISSUE TITLE
Duda graficos pregunta 2 - tarea 2

### ISSUE THREAD

**Issue by Juancagp** [IIC2613-Inteligencia-Artificial-2023-1/Syllabus#26]
Hola, tengo la duda sobre el enunciado que dice que el gráfico debe reportar para cada problema y cada variante el tiempo que tardó en ejecutarse. En mi caso la diferencia de tiempo entre las variantes entre 1 brazos y las otras 2 variantes de cada problema es super grande y por ende el gráfico queda muy disparejo como en el eje, haciendo imposible que se pueda ver el valor, al menos graficamente. En vez de un gráfico podría ser una tabla donde se reporten todos los valores segun cada variante? 

así es como me queda el gráfico:
![image](https://user-images.githubusercontent.com/81201399/232380726-41f4a693-64c1-4e92-ba88-18636b43d973.png)

Estaba pensando que quizas en el informe puedo ilustrar el gráfico y la tabla juntas, para que se pueda notar graficamente la diferencia y con la tabla ser más explicito en los valores.

**Comment by cafigueredo** [comment]
Hola @Juancagp 

No hay problema en que pongas la tabla, pero el gráfico si lo debes poner ya que eso es lo que pide el enunciado. Recuerda tambien mostrar tu analisis en el parrafo de conclusiones.
