### ISSUE TITLE
Gráficos P2.2

### ISSUE THREAD

**Issue by Fernanda1232123** [IIC2613-Inteligencia-Artificial-2023-1/Syllabus#28]
Hola,

Hay que hacer un gráfico con los tiempos que se demora en encontrar solución.
En los casos que tengo, hay mucha diferencia entre el que más se demora y el que menos se demora. Esto resulta en que lo tiempos menores a 2 segundos no se representan en el gráfico.

¿Está bien?
¿Puedo hacer un gráfico por cada número de brazos?

**Comment by cafigueredo** [comment]
Hola @Fernanda1232123 

Puedes agregar de forma extra un grafico en que se represente más claramente la información. Pero de todas maneras debes realizar el grafico que se solicita por enunciado.
