### ISSUE TITLE
Tarea 2 - Pregunta 2.1

### ISSUE THREAD

**Issue by pabloalvarez67** [IIC2613-Inteligencia-Artificial-2023-1/Syllabus#29]
Hola! tengo la duda de como calcular el score de mi nuevo tablero al realizar una nueva jugada con el game_copy.
Si la idea es comparar ese score con el definido anteriormente (que en el caso de max es -infinito), como puedo hacerlo sin tener que entrar en recursiones innecesarias de jugadas que son "malas" para un jugador?

**Comment by CGR0** [comment]
Hola! Disculpa por no haber respondido antes. 
Para implementar el algoritmo minimax no te tienes que preocupar de calcular el score, este se calcula cuando se llegan a las condiciones de término (se llega a la profundidad máxima de recursión o algún jugador resulta victorioso) que se definen entre las líneas 10 a 27 del archivo minimax.py. 
Espero haberte ayudado!
