### ISSUE TITLE
Codigo de A* usado en clases

### ISSUE THREAD

**Issue by FelipeRiveraC** [IIC2613-Inteligencia-Artificial-2023-1/Syllabus#30]
Hola,

me gustaria saber si el codigo de A* usado en clases y mencioando en el enunciado se ecnuentra disponible para poder revisarlo. Gracias

**Comment by dfloreaa** [comment]
Hola, voy a consultar en qué quedo esto, personalmente te diría que esperes un anuncio dentro de los próximos días al respecto
