### ISSUE TITLE
Retorno A* Solver.search

### ISSUE THREAD

**Issue by Martinrsts** [IIC2613-Inteligencia-Artificial-2023-1/Syllabus#32]
Hola,

No me queda claro que debe retornar AStarSolver.search en la pregunta 1. Lo que yo creería es que debe retornar el nodo final o una listas de pasos, pero sol en BallSortSolver pareciera ser que es una lista de lista de listas.

**Comment by dfloreaa** [comment]
Hola, probablemente haga un anuncio entrado en más detalles al respecto, pero la idea es que este método retorne una tupla de tres elementos:

`return node.trace(), self.expansions, self.end_time - self.start_time`

Donde el único elemento realmente necesario para la solución (y poder visualizarla) es el output del método `.trace()` sobre el nodo final al resolver el puzzle, esto corresponde a una lista con todos los movimientos realizados para llegar a este estado desde el estado inicial.

`self.expansions` corresponde al número total de expansiones llevadas a cabo para completar la búsqueda (se le suma uno cada vez que expandimos un nodo), mientras que la última variable corresponde al tiempo demorado en encontrar una solución. Ambos sirven para mantener rastro del desempeño del algoritmo y poder contrastar entre distintas heurísticas.

Por favor coméntame si tienes más dudas al respecto :)
