### ISSUE TITLE
Duda repeated color heuristic

### ISSUE THREAD

**Issue by pabloalvarez67** [IIC2613-Inteligencia-Artificial-2023-1/Syllabus#33]
Hola, como deberia funcionar aquella heuristica en caso de que en un tubo todas las bolas sean distintas?
 O también en el caso de que haya más de 1 color con la misma cantidad? Ejemplo: [4,4,3,6,3]
 
 Saludos y gracias de antemano.

**Comment by dfloreaa** [comment]
Hola, en ese caso (según la intuición de la heurística) el costo debería ser de `len(tubo) - 1`. Esto debido a que la heurística trata de reflejar "el mínimo número de movimientos necesarios para que el tubo sea de un solo color".

Similarmente y teniendo eso en consideración, el caso que propones para [4, 4, 3, 6, 3] debería retornar 3.

**Comment by pabloalvarez67** [comment]
Buena Daniel, gracias.
Otra duda respecto a las heurísticas, cuando demostramos su admisibilidad, es dado el contexto del problema? Vale decir, tomando en consideración las características del problema y que se está haciendo en un algoritmo de A*?

**Comment by dfloreaa** [comment]
Efectivamente, asumiendo las restricciones que tiene el problema actualmente (puedes hacer solamente un movimiento a la vez y solo se puede sacar la primera bola de cada frasco para moverla).

Más allá de que se esté llevando una búsqueda de A* a cabo, buscamos que demuestren por qué la heurística es admisible, es decir, que la estimación que provee la heurística _h_ entre dos estados **no sea nunca superior** al costo óptimo para llegar desde uno a otro $$h(s, s') \leq h^*(s, s')$$

**Comment by pabloalvarez67** [comment]
> Efectivamente, asumiendo las restricciones que tiene el problema actualmente (puedes hacer solamente un movimiento a la vez y solo se puede sacar la primera bola de cada frasco para moverla).
> 
> Más allá de que se esté llevando una búsqueda de A* a cabo, buscamos que demuestren por qué la heurística es admisible, es decir, que la estimación que provee la heurística _h_ entre dos estados **no sea nunca superior** al costo óptimo para llegar desde uno a otro h(s,s′)≤h∗(s,s′)

Comprendo, pero dado a que uno en el programa calcula la heurística de un estado s, puedo decir que la heurística de pasar de un estado s a s' sea la suma de la heurística en ambos estados? vale decir,
_h(s,s') = h(s) + h(s')_

**Comment by dfloreaa** [comment]
Respecto a la notación, una heurística computa una aproximación al costo de pasar desde un estado $s$ a un estado $s'$ (en la tarea $s'$ siempre es el estado final), en ese sentido $h(s, s')$ existe, pero $h(s)$ no (o haría referencia al costo aproximado desde $s$ hasta el estado final).

Sobre tu pregunta, **depende del tipo de heurística**. Por ejemplo, en el contexto de la tarea, tomemos la heurística número de bolitas diferentes entre dos estados. Ahora, tomaremos 3 estados distintos: un estado inicial $s$, un estado intermedio $q$ y un tercer estado $s'$.

Así tendremos:
- $s:$
![image](https://github.com/IIC2613-Inteligencia-Artificial-2023-1/Syllabus/assets/62019645/fdaf638b-1d1a-454b-9a9f-19c34d318fb1)

- $q:$
![image](https://github.com/IIC2613-Inteligencia-Artificial-2023-1/Syllabus/assets/62019645/14e6ea74-cde0-4bb0-95a1-4b517279f7a9)

- $s':$
![image](https://github.com/IIC2613-Inteligencia-Artificial-2023-1/Syllabus/assets/62019645/86ad92aa-add1-4430-8697-78e26b87f530)

Podemos computar el valor de la heurística entre distintas configuraciones:
- $h(s, q) = 1$
- $h(q, s') = 3$
- $h(s, s') = 1$

Notamos que en este caso $h(s, s') \neq h(s,q) + h(q,s')$

En resumen, **no**, no puedes decirlo.
