### ISSUE TITLE
Caso Base Minimax

### ISSUE THREAD

**Issue by ghost** [IIC2613-Inteligencia-Artificial-2023-1/Syllabus#35]
Hola! tengo una duda respecto al principio del código de minimax.
Este siempre que la profundidad sea 0, retornará la jugada None,None. Esto hace que el programa se caiga porque debiese de ser un movimiento válido.

Me pasa que siempre retorno el caso base, ya que si el player 2 (minimax) comienza la recursión nunca llega a un caso de que me disminuya en algo mi puntaje con alguna jugada suya en el primer turno.

Por ende, mi duda es si esa parte hay que dejarla asi? o hay que editar también ahí, aunque no tenga # Complete.

**Comment by CGR0** [comment]
Hola!
Tienes que dejar el caso base como está, el movimiento que se retorna es None porque cuando se llega a la profundidad máxima no se eligen más movimientos.
Si te sirve piensa que el algoritmo cuando se adentra en la profundidad solo le interesa el score y no el movimiento, ya que esos movimientos no los podría ejecutar porque serían "futuros". El movimiento que te interesa retornar es el que maximice o minimice el puntaje para la recursión menos "profunda". Por lo tanto cuando uno hace la recursión solo interesa buscar el mejor score para ejecutar un movimiento que se tenga disponible en esa jugada.
Espero haberte ayudado, cualquier cosa no dudes en volver a consultar!

**Comment by pabloalvarez67** [comment]
Si perfecto! entiendo cuál es la idea. El tema es que al retornarme None, None para el último valor de la última iteración de minimax, se retornarán estos valores nulos sucesivamente hasta que el último minimax también retornará el movimiento None, None. Esto me ocurre a pesar de haber obtenido puntajes y "buenas jugadas" para el min (considerando que yo soy max) entremedio.
Así, el programa se cae porque no se puede ejecutar una jugada None, None. Quizás estoy retornando mal?
Gracias!

**Comment by CGR0** [comment]
Entiendo tu pregunta, pero es difícil responderte sin darte directamente más información de la que debería.
Tienes que fijarte bien en lo que retornas, y está mal que al terminar de ejecutar la función de minimax el movimiento retornado sea None, None. Lo único que te puedo decir es que te debería importar únicamente la jugada que se pueda jugar en el momento en que se ejecuta minimax y el posible score al que puede conducir esta jugada.
Avísame si todavía tienes dudas al respecto.
