### ISSUE TITLE
T2 P2.3 código minimax

### ISSUE THREAD

**Issue by Martinrsts** [IIC2613-Inteligencia-Artificial-2023-1/Syllabus#36]
Hola,
En el código para minimax la línea 31 dice:
``` 
maximize = True if game.turno.color == "blanco" else False
```
Eso no hace que minimax no funcione para el jugador negro? Porque si es así no podríamos comparar la ventaja para el que sea primero.

**Comment by mecifuentes** [comment]
Same acá, tuve que cambiar ese valor a "negro" para que funcionara en el jugador 2

**Comment by Martinrsts** [comment]
Caché que en verdad no afecta, porque no importa quién use el minimax, si está en el turno de blanco se quiere maximizar el score de blanco y si está en el turno de negro se quiere maximizar el score de negro, que es lo mismo que minimizar el score de blanco.

**Comment by CGR0** [comment]
> Caché que en verdad no afecta, porque no importa quién use el minimax, si está en el turno de blanco se quiere maximizar el score de blanco y si está en el turno de negro se quiere maximizar el score de negro, que es lo mismo que minimizar el score de blanco.

Exáctamente!
