### ISSUE TITLE
Wagdy heuristic

### ISSUE THREAD

**Issue by mati-giddings** [IIC2613-Inteligencia-Artificial-2023-1/Syllabus#37]
Hola! En el caso de tener un tubo como `[1,1,2,3,3,4]`, los pares consecutivos de distinto color serían `(1,2), (2,3) y (3,4)`? o solo habría que considerar un par entre `(1,2) y (2,3)`?

**Comment by dfloreaa** [comment]
Hola, deberás considerar `(3,4)` también. La intuición es que necesitarás al menos 2 pasos para poder ordenar ese tubo (uno para sacar la bola de arriba y otro para colocar la correcta en su lugar).
