### ISSUE TITLE
Problema con instalar pygame

### ISSUE THREAD

**Issue by pedro-gigoux** [IIC2613-Inteligencia-Artificial-2023-1/Syllabus#39]
Hola, escribo debido a que nose por qué no me esta funcionando correr el main de la pregunta 2, diciendome que no existe la libreria pygame, siendo que la instale con pip y me salio que se instalo correctamente. ¿Puede ser que sea un problema con la version de python?

**Comment by CGR0** [comment]
Estás usando WSL? En ese caso es normal que tengas problemas con pygame y te recomendaría correr la tarea en otro entorno o puedes investigar sobre XLaunch que sirve para mostrar este tipo de interfaces con WSL. Igualmente yo creo que sería más fácil correrlo en el entorno de windows (python funciona muy bien en windows).
Si no estás usando WSL no sé realmente que te podría estar pasando, necesitaría que me comentes más de tu error para ayudarte a encontrar una solución.

**Comment by pedro-gigoux** [comment]
No creo que este utilizando WSL, tengo la carpeta en escritorio y lo estoy corriendo normalmente

**Comment by CGR0** [comment]
Sigues con el problema? Si es que el problema persiste te puedo decir que el visualizador no es estrictamente necesario para la ejecución del programa. Basta con cambiar los parámetros y poner en False el visualizador. El visualizador solo sirve para ver de forma fácil la ejecución del programa.

**Comment by pedro-gigoux** [comment]
Si ya me resulto, pero gracias igual
