### ISSUE TITLE
Duda open.clear()

### ISSUE THREAD

**Issue by marcotroncoso** [IIC2613-Inteligencia-Artificial-2023-1/Syllabus#41]
No entiendo que hace open.clear(), debería vaciar la open pero solo cambia el size a 0. Eso está bien? porque se supone que deja vacia la estructura completa. Quedo atento.

**Comment by dfloreaa** [comment]
Hola, efectivamente el método solo hace lo que indicas. Ahora bien, el resto del código está pensado para considerar esto y rearmar la estructura desde cero si el método es ejecutado, por lo que cumple el funcionamiento que se indica en #34.

En todo caso, no es necesario utilizar este método en tu implementación de `search()` (sería necesario hacer un `self.open.clear()` al comienzo de la búsqueda para poder replicarla muchas veces, afuera de eso no es necesaria).
