### ISSUE TITLE
Tiempos de ejecución BallSortSolver

### ISSUE THREAD

**Issue by Martinrsts** [IIC2613-Inteligencia-Artificial-2023-1/Syllabus#43]
Hola,

¿es normal que el algoritmo A* se demore mucho con el mapa 5? Lo dejé ejecutando por 15 minutos y no llegó a la solución.

Si es normal como podremos hacer la comparación empírica de heurísticas si hay que hacer al menos 5 ejecuciones por cada mapa para cada heurística?

**Comment by dfloreaa** [comment]
Hola, efectivamente noté que el mapa 5 se demora bastante en resolver. Lo comenté con el equipo docente del curso y deberíamos hacer un aviso al respecto mañana (probablemente lo cambiemos por un puzzle más fácil de resolver).

Un saludo y éxito con tu tarea :))

**Comment by Martinrsts** [comment]
Con el mapa 3 y el mapa 2 también los ejecuté por 10 minutos y no encontró la solución, también es normal?
Y cuando en el enunciado dice: "Toma una muestra de al menos 5 ejecuciones en cada caso", se refiere a 5 ejecuciones por mapa, algoritmo y heurística (o sea 100 ejecuciones en total) o 5 ejecuciones con un mapa distinto cada una para cada algoritmo y heurística (o sea 20 ejecuciones en total)

**Comment by dammr54** [comment]
¿se debe ejecutar el mapa new_map.json también que se encuentra en esa carpeta ?
Continuo la misma línea del compañero, ejecute el mapa 2 y lleva 30 minutos en ejecución sin encontrar una solución

**Comment by dfloreaa** [comment]
Hola @Martinrsts y @dammr54 , vamos a cambiar los mapas entregados para que sean resueltos en menor tiempo. Mil y una gracias por el comentario, resulta que el solver que usé para revisarlos es distinto a lo que le pedimos implementar y los corría más rápido.

**Comment by dfloreaa** [comment]
@dammr54 respecto al mapa `new_map.json`, no, ese es el mapa por defecto de prueba al correr `puzzle_generator.py`, voy a eliminarlo del repo de la tarea.

**Comment by dfloreaa** [comment]
@Martinrsts por lo que veo, afuera del mapa 5, todo el resto de los mapas deberían ejecutarse en un tiempo menor a 10 segundos utilizando una heurística. ¿Estás seguro de que tu implementación del algoritmo y la heurística es correcta? Te recomiendo hacer tus propios ejemplos con `puzzle_generator.py` y hacer prints de las expansiones llevadas a cabo.

**Comment by dfloreaa** [comment]
@Martinrsts sobre lo segundo, se refiere a 5 ejecuciones (5 mapas distintos) para cada combinación de algoritmo-heurística, en total son 20 tests (cada ejecución para una combinación algoritmo-heurística debe ser comparada con las de las otras combinaciones).

**Comment by dfloreaa** [comment]
Hola @dammr54 se refiere a la parte anterior, la Actividad 4. Voy a corregir el enunciado
