### ISSUE TITLE
Columnas Bump DCCheep

### ISSUE THREAD

**Issue by BValdes16** [IIC2613-Inteligencia-Artificial-2023-1/Syllabus#44]
Hola, estaba probando los resultados del minimax con diferente cantidad de columnas en el juego, y creo que es bastante sensible. ¿Debiésemos incluir cómo reacciona el sistema a esta cantidad, o simplemente utilizamos las 13 columnas por default?

**Comment by CGR0** [comment]
Para efectos de esta tarea si te corre con las 13 columnas por defecto debiera estar bien. Esas columnas por defecto son solo para que se pueda correr con el visualizador.
