### ISSUE TITLE
Consulta valid_moves de minmax

### ISSUE THREAD

**Issue by jburdiles** [IIC2613-Inteligencia-Artificial-2023-1/Syllabus#45]
Es normal que las decisiones de minmax cambien dependiendo del orden de las tuplas en valid_moves?, o es un error?

**Comment by CGR0** [comment]
Hola!
Es totalmente normal y mientras el juego se ejecute correctamente no te deberías preocupar.

**Comment by jburdiles** [comment]
Ahh ok, y para el estudio analitico esta bien si uso valid_moves ordenado o desordenado?

**Comment by CGR0** [comment]
Puedes hacerlo con cualquiera de las dos opciones. Te recomiendo especificar la opción que elegiste en el informe y que tengas en cuenta tu decisión en la última parte del informe.

**Comment by jburdiles** [comment]
Vaale, muchas graciaas!!
