### ISSUE TITLE
Versión Clingo

### ISSUE THREAD

**Issue by Fernanda1232123** [IIC2613-Inteligencia-Artificial-2023-1/Syllabus#5]
Hola,

Instalé la versión de Clingo 5.6.2 en MacOS. Pero en la cápsula se instala la versión 5.4.0, así que me queda la duda ¿Cuál se va a usar en el curso?

Gracias!

**Comment by vicentevegaulloa** [comment]
Hola!

No se como lo podrías hacer para bajar de versión, pero estuve investigando y para los programas con los que van a trabajar, no deberían tener problemas si ocupan cualquiera de las dos versiones.
