### ISSUE TITLE
Consulta sobre "same_as_bottom_heuristic"

### ISSUE THREAD

**Issue by ExRage2000** [IIC2613-Inteligencia-Artificial-2023-1/Syllabus#51]
Hola, me surgió una duda ya que vi que en el código base de BallSortSolver.py aparecía la función "same_as_bottom_heuristic", supuestamente importada de heuristics.py
![image](https://github.com/IIC2613-Inteligencia-Artificial-2023-1/Syllabus/assets/69613733/e4bab87d-23ee-4a13-bd2d-212ce3778401)
Sin embargo, al revisar, noté que esa función no aparece ni en el archivo base de heuristics.py ni en el enunciado (como para implementarlo)

Me gustaría saber si esto es un error o si estoy pasando algo por alto, ya que actualmente si ejecuto el código me tira un Error diciendo que la función (método o atributo) no existe
![image](https://github.com/IIC2613-Inteligencia-Artificial-2023-1/Syllabus/assets/69613733/08529ded-0dcc-4c98-a8ed-b4a3d4396b19)

**Comment by dfloreaa** [comment]
Hola, efectivamente, la heurística es inexistente en el archivo `heuristics.py` y debes cambiarla por una que si existe (y que implementaste). Si aún no implementas ninguna utiliza `heuristics.no_heuristic`
