### ISSUE TITLE
Ganador BumpSheep

### ISSUE THREAD

**Issue by marcotroncoso** [IIC2613-Inteligencia-Artificial-2023-1/Syllabus#53]
Mi duda es, un jugador "random" puede ganarle a un "minimax" con un iq de 5 por ejemplo? Si llega a pasarme eso, mi implementación de minimax esta mal?

**Comment by blanca-romero** [comment]
Hola! Es posible que pase esto, no significa que haya algo mal con tu implementación. Incluso podrías indagar por qué pasa esto (revisando la implementación del juego y del algoritmo) y agregarlo a tu análisis.
