### ISSUE TITLE
Analisis P2.3

### ISSUE THREAD

**Issue by IgnAMS** [IIC2613-Inteligencia-Artificial-2023-1/Syllabus#54]
Hola! En la pregunta 2 se pide un analisis de:

- 10 juegos con 5 filas random vs minimax de profundidad 3. 
- 10 juegos con 5 filas minimax vs minimax de la misma profundidad.
Ante esto, en el primer caso, se espera que se analiza con las mismas cantidad de columnas? En ese caso se consideran 13 columnas?  
Para el segundo problema, se espera que se analice como varían las jugadas con diferentes profundidades (que sea la misma para ambos)? 

Saludos!

**Comment by blanca-romero** [comment]
Hola! el tablero "default" tiene 13 columnas (por la visualización) pero si quieren cambiar la cantidad de columnas pueden hacerlo, **recuerden que todo debe quedar bien documentado en su informe**.

En la segunda pregunta se busca que hayan 2 jugadores *minimax* con la misma profundidad (cualquiera) y deben analizar como cambian con distintos largos de tablero, es decir con **distinta cantidad de columnas** (deben hacer esta parte sin la visualización).
