### ISSUE TITLE
Duda sobre la implementación de las heurísticas.

### ISSUE THREAD

**Issue by TTrincado** [IIC2613-Inteligencia-Artificial-2023-1/Syllabus#57]
Hola! Tenía una duda sobre qué pasaba si en un tubo se tenía solo una bola. En este caso por enunciado de la repeated_color-_heuristic tendría un costo de 0 para el movimiento, pero como se mencionó en otra issue y en el FAQ, la heurística "retorna el mínimo número de movimientos necesarios para poder remover todas las bolas de un tubo hasta que sean todas de un mismo color (sin considerar su orden). Tomando esto en cuenta, la salida deberá ser len(tubo) - 1.". Por esta definición el costo también sería 0, pero encuentro un poco contra intuitivo que un movimiento para sacar la bola o agregar al tubo [1] tenga un costo 0 y no 1.
¿Sería 0 o 1?. Creo que la duda aplica a su vez para la wadgy_heuristic. ¿Para ambos casos sería 0?

**Comment by dfloreaa** [comment]
Hola, la heurística retornaría 0 dado que todas las bolas del tubo son del mismo color (que es la mayoría). Lo mismo para Wadgy, dado que no existen pares consecutivos de bolas.

Un saludo :))
