### ISSUE TITLE
Límite de planas en informe

### ISSUE THREAD

**Issue by MartinCastillo** [IIC2613-Inteligencia-Artificial-2023-1/Syllabus#59]
Hola!

Si hago un anexo para incluir tablas en el informe de la tarea 2 se cuenta para el límite de planas?

**Comment by dfloreaa** [comment]
Hola, no, pero trata de incluir todo lo necesario en el informe y que el contenido del anexo sea solo complementario (si no, deja de ser un anexo y pasa a ser parte del informe).

**Comment by MartinCastillo** [comment]
vale, gracias
