### ISSUE TITLE
Limite pag parte 1 

### ISSUE THREAD

**Issue by JRichi99** [IIC2613-Inteligencia-Artificial-2023-1/Syllabus#62]
Tengo entendido que para la parte 2, el limite es de 3 planas. Sin embargo, no encuentro especificacion para la parte 1 (DCColor), donde tiene q haber demostraciones y discucion de resultado.

**Comment by dfloreaa** [comment]
Hola, no hay límite. En todo caso, por favor tengan prudencia con sus respuestas.
