### ISSUE TITLE
Comparación entre BFS y A*

### ISSUE THREAD

**Issue by based-on-what** [IIC2613-Inteligencia-Artificial-2023-1/Syllabus#63]
Hola, para comparar entre estos dos algoritmos, ¿también deben compararse usando **ambas heurísticas**? ¿O puedo hacerlo con `no_heuristic`?

Saludos y muchas gracias.

**Comment by dfloreaa** [comment]
Hola, efectivamente, similar al inciso anterior de la tarea.
