### ISSUE TITLE
Tarea 3 - Mostrar imágenes en Jupyter Notebook

### ISSUE THREAD

**Issue by Maratripa** [IIC2613-Inteligencia-Artificial-2023-1/Syllabus#66]
Hola! En el enunciado dice que debemos mostrar imágenes. Se puede usar la librería pillow o IPython para esto?

**Comment by Maratripa** [comment]
O opencv

**Comment by ignaciovilla** [comment]
Hola! Si pueden usar la que necesiten.
Saludos!
