### ISSUE TITLE
Tarea 3 - ¿Puedo trabajar el .ipynb localmente?

### ISSUE THREAD

**Issue by danvillablanca** [IIC2613-Inteligencia-Artificial-2023-1/Syllabus#67]
Hola,

Dado que he tenido dificultades para efectivamente desocupar el espacio de Google Drive mediante mi cuenta universitaria, presento problemas a la hora de trabajar el .ipynb desde la página web. Resolver estos inconvenientes me tomará un tiempo que quisiera evitar.

Dado que cuento con el acceso a los recursos necesarios para la tarea 3 a nivel local, quisiera saber si es posible desarrollar la tarea 3 a nivel local (esto es, instalando las librerías en el computador, descargando la carpeta Avengers 1 en el computador y trabajar con VSC). Esto me significaría una reducción importante de tiempo de trabajo destinado a la Tarea 3.

Esto afectaría en el desarrollo esperado de la siguiente forma: En lugar de obtener las primeras líneas de comando, se usarían los archivos localmente, todo lo demás debiese funcionar de la forma esperada.

Saludos,
Dan.

**Comment by weibac** [comment]
Me sumo a la pregunta.

**Comment by ignaciovilla** [comment]
Hola! 
Dos cosas importantes. La primera es que pueden trabajar en colab con otra cuenta de Gmail distinta a la UC y no hay problemas.

Lo segundo, no hay problema con trabajar local mientras entreguen un jupyter Notebook con las celdas ejecutadas.

Saludos!
