### ISSUE TITLE
Tarea 3 - Imágenes mal clasificadas en el dataset

### ISSUE THREAD

**Issue by weibac** [IIC2613-Inteligencia-Artificial-2023-1/Syllabus#68]
La afirmación ```Cada una de estas carpetas contiene exclusivamente imágenes de las caras de su respectivo Vengador``` presente en el enunciado no se cumple al 100%.

Algunos ejemplos:
- ```Avengers\ 1_\black_widow\face21651_1.png``` en realidad es de Hawkeye
- ```Avengers\ 1_\hulk\face85981_0.png``` en realidad es de Iron Man
- ```Avengers\ 1_\iron_man\face40005_0.png``` no contiene caras

¿Cómo se espera que manejemos estas limitaciones del set de datos? ¿Se espera que hagamos alguna especie de filtrado o detección de outliers, o basta con asumir la pérdida de rendimiento?

**Comment by ignaciovilla** [comment]
Hola! Puedes manejarlas a tu criterio, siempre que lo justifiques adecuadamente.
Saludos
