### ISSUE TITLE
Actividad 1: analisis de la distribucion de las clases

### ISSUE THREAD

**Issue by clangoi** [IIC2613-Inteligencia-Artificial-2023-1/Syllabus#69]
Hola, cuando en la parte de la Actividad 1 dicen "analisis de la distribucion de las clases en el dataset" se refieren a las características de las clases o a la cantidad de datos por clase?

**Comment by ignaciovilla** [comment]
Hola! A la cantidad de instancias de cada clase! 
Saludos
