### ISSUE TITLE
Duda actividad 2 

### ISSUE THREAD

**Issue by JRichi99** [IIC2613-Inteligencia-Artificial-2023-1/Syllabus#70]
En el enunciado dice: deberán manejar adecuadamente los casos en que no se obtienen landmarks, mostrando la cantidad de imágenes para las que estos no se obtuvieron. Adicionalmente, deberán decidir qué hacer con ellas de manera justificada, explicitando los motivos de cualquier modificación y/o eliminación. 

Mi pregunta es: puedo pasar al modelo una foto la cual no tiene landmark?, segun entiendo no se puede porque el modelo trabaja sobre los landmark. Pero en el enunciado dice modificaciónes, entonces si la modificando la foto no encuentro manera de que consiga extraer un landmark entonces se debera descartar para el entrenamiento o no?

**Comment by ignaciovilla** [comment]
Hola! Queda a tu criterio que hacer con esa foto mientras lo justifiques adecuadamente.
Saludos
