### ISSUE TITLE
Error Colab

### ISSUE THREAD

**Issue by JRichi99** [IIC2613-Inteligencia-Artificial-2023-1/Syllabus#71]
No se puede establecer conexión con el backend de la GPU
Actualmente no puedes conectarte a una GPU debido a los límites de uso de Colab.

Me aparece eso, significa que desde ahi ya no puedo continuar trabajando?

**Comment by mtaguero** [comment]
A mí igual me pasó lo mismo. Parece que hay que esperar horas/días/semanas según el uso que le des para conectarte a otra GPU. En ese caso, estaba pensando en lo que se preguntó en la issue #67. Sería genial igual que se hiciera un anuncio sobre qué hacer en este caso, porque nos limita harto el tiempo de trabajo que designamos para la tarea :(

**Comment by clangoi** [comment]
Yo me conecté desde otra cuenta, mientras me volvía a dejar usar la GPU

**Comment by ignaciovilla** [comment]
Hola! Lo que pueden hacer es descargar su Notebook, y luego usar otra cuenta de Gmail para entrar a colab y abren su trabajo desde ahí. 
El tiempo se usó de GPU se reinicia cada día así que para que lo tengan en cuenta.

Por otro lado, tengan presente que no todas las secciones de la tarea necesitan de GPU. Por lo que pueden ir guardando sus datasets a medida que los van modificando, y usar la GPU cuando realmente la necesiten.

Mucho éxito con la tarea
