### ISSUE TITLE
[IMPORTANTE CONTROLES!] Nota Final Controles

### ISSUE THREAD

**Issue by paulmacguire** [IIC2613-Inteligencia-Artificial-2023-1/Syllabus#73]
Hola! Quería saber si existe la posibilidad de que se puedan borrar 3 controles en vez de 2, considerando el final de semestre que está muy pesado, y el estrés que conlleva no saber las notas acumuladas al momento de rendir los controles es algo que influye de manera significativa nuestro rendimiento. Es por eso que quería pedir encarecidamente si pueden tomar en cuenta nuestra situación y que se pueda llevar a cabo esto.

Gracias de antemano y espero que no sea un dolor de cabeza para ustedes.

**Comment by larryuc** [comment]
Me sumo a la petición,  en particular considerando el control 9 dónde la proporción de rojos fue de 120 sobre 24 azules, justo coincidió con que no había un control de repaso en canvas asociado específicamente a esa materia previa a SVM.

**Comment by JRichi99** [comment]
Me sumo

**Comment by mati-gonz** [comment]
Me sumo a la petición. Además, quería pedir si es que es posible que puedan subir las pautas, o entregar de vuelta los controles, ya que a esta altura ya no recuerdo que fue lo que respondí y tampoco hay forma de saber en qué me equivoqué.

**Comment by dammr54** [comment]
Me sumo también a la petición, considerando que tampoco siempre se tuvo la facilidad de llegar puntualmente a las 8:30 a rendir el control debido a diversos factores externos a mi :( (no soy de Santiago)

**Comment by RadiosMark** [comment]
me sumo
