### ISSUE TITLE
Tarea 3 - Set de Datos

### ISSUE THREAD

**Issue by marcotroncoso** [IIC2613-Inteligencia-Artificial-2023-1/Syllabus#74]
Hola,

Hay varias imagenes que estan mal ubicadas. Mi pregunta es, estan ahi a proposito? O fue un error que debemos arreglar? Quedo atento.

**Comment by ignaciovilla** [comment]
Hola! Puede haber sido un error. Lo importante es que independiente de lo que decidas hacer con ellas, debes explicar y justificar tu decisión.
Dime si eso responde tu duda.
Saludos!

**Comment by gecoli** [comment]
¡Hola! En el hipotético caso de que las elimine, ¿Tendría que hacerlo mediante código o puedo decir 'eliminé manualmente tal y tal foto'?

**Comment by ignaciovilla** [comment]
Hola! Idealmente mediante código para que puedas rehacerlo en caso de que tengas algún problema.
De todas formas, muestra las fotos que vas a eliminar antes de hacerlo, para que sepamos bien cual era el problema.
Por otro lado, en vez de eliminarlas podrías cambiarlas a su carpeta correspondiente, lo cual podría ser más beneficioso.
Avísame si eso responde tu duda.
