### ISSUE TITLE
Uso de librerias

### ISSUE THREAD

**Issue by clangoi** [IIC2613-Inteligencia-Artificial-2023-1/Syllabus#76]
Hola, tengo una consulta respecto del uso de librerias, en el enunciado dice "usaremos principalmente tres librerias para esta tarea" esto es "pueden usar otras librerias que no se encuentran mencionadas"? Puedo usar skimage?

**Comment by clangoi** [comment]
Puedo usar skimage?

**Comment by ignaciovilla** [comment]
Si no hay problema! Solo comenta para que la usaras.
Saludos.
