### ISSUE TITLE
Tratamiento landmarks

### ISSUE THREAD

**Issue by 4n1t4** [IIC2613-Inteligencia-Artificial-2023-1/Syllabus#77]
Hola , una duda en la actividad 2 sería valido generar una nueva clase que sea no_landmarks, para que de esta manera, cuando entrene el modelo el azar de la exactitud que me genere al clasificar una imagen dado q esta no posee landmark no sea tan aleatorio o esto traería muchos problemas de sobreajuste ?

**Comment by ignaciovilla** [comment]
Hola! No entendí muy bien tu pregunta, pero al no tener landmarks será imposible extraerle features a esa imagen (a menos que estés usando otro tipo de features), por lo que veo difícil que puedas entregárselas al modelo. 
Por otro lado, las imágenes sin landmarks pueden pertenecer a cualquier clase, por lo que agregarlas como una clase nueva debería empeorar el resultado del modelo, al hacer que este "confunda".
Por ejemplo, imagina que tengo dos fotos del capitán américa, una sin landmarks y otra con landmarks. Si le entrego la foto sin landmarks al modelo, este debería predecir que es de la clase "captién américa" o "sin landmarks"? 
Avísame si eso responde a tu duda.
