### ISSUE TITLE
Overfitting en Modelos

### ISSUE THREAD

**Issue by Juancagp** [IIC2613-Inteligencia-Artificial-2023-1/Syllabus#78]
Hola, tengo la duda si cuando estamos entrenando los modelos, hay que intentar disminuir el overfitting con alguna tecnica. o solo debemos dedicarnos a configurar los parametros que consideremos más relevantes y elegir el modelo que de mayor accuracy, sin tomar en cuenta el posible overfitting.

**Comment by ignaciovilla** [comment]
Hola! Siempre se deben tener en cuenta el overfitting, aunque en general es más fácil evaluar si existe sobre ajuste después de los resultados. 
Por lo tanto, es muy bueno planificar esto antes de hacer un modelo, pero es igual de importante tenerlo en cuenta en el análisis posterior.
Avísame si eso responde a tu duda.
