### ISSUE TITLE
Uso de metodo GridSearchCV

### ISSUE THREAD

**Issue by Juancagp** [IIC2613-Inteligencia-Artificial-2023-1/Syllabus#79]
Hola! googleando llegue a este metodo de sklearn.model_selection  (from sklearn.model_selection import GridSearchCV). donde en resumen le entrego al metodo el modelo a utilizar y un diccionario con los parametros a cambiar. se supone que este metodo te entrega el mejor modelo encontrado según los parametros que le entrego para cambiar. pero probando con unos cuantos parametros llegó a tardarme aprox 10 minutos, pero si me encontró un modelo con , mejor rendimiento que el default del modelo. Es legal ocupar este método? más que nada por la cantidad de tiempo que llega a tardar

**Comment by ignaciovilla** [comment]
Es importante que veas los resultados de todos los modelos que estas probando, no solo del mejor posible. 
Mientras puedas hacer eso está bien.
