### ISSUE TITLE
Repositorios Tareas

### ISSUE THREAD

**Issue by pabloalvarez67** [IIC2613-Inteligencia-Artificial-2023-1/Syllabus#8]
Hola! estoy teniendo problemas clonando mi repositorio personal de la tarea, usando el método convencional de git clone. Pregunto porque no sé si a alguien mas le pasa, o si solamente soy yo el que está con problemas actualmente.
Gracias!

**Comment by vicentevegaulloa** [comment]
Hola @pabloalvarez67 !

Estás clonando el repo que se genera clickeando el link que estaba en el anuncio? O desde el repo público llamado Tarea 1?

**Comment by pabloalvarez67** [comment]
El que se genera desde el anuncio, que en mi caso es tarea-1-2023-1-pabloalvarez67

**Comment by vicentevegaulloa** [comment]
Podrías compartir un screenshot del error que te arroja la terminal? Y si puedes explicar más en detalle lo que ocurre también te lo agradecería

**Comment by pabloalvarez67** [comment]
Simplemente me dice que el repositorio no ha sido encontrado: 
<img width="693" alt="Captura de Pantalla 2023-04-05 a la(s) 12 11 09 p  m" src="https://user-images.githubusercontent.com/62023649/230140542-ac014c0e-1e82-464c-ba69-d3ba678a0eb1.png">

**Comment by vicentevegaulloa** [comment]
Que extraño, yo acabo de clonar tu repo sin problemas en mi computador. Puede que sea un problema de red. Intenta clonarlo desde otra red, o quizás otra terminal. También podrías asegurarte de estar otorgando todos los permisos necesarios. Si no te funciona, te recomiendo clonar el [repo template](https://github.com/IIC2613-Inteligencia-Artificial-2023-1/Tarea-1) que se encuentra en el github del curso. Por mientras podrías trabajar en local con los archivos del template (que son los mismos de tu repo personal) y si de aquí a la próxima semana no te funciona, escríbeme al correo del curso.

**Comment by pabloalvarez67** [comment]
Dale gracias! definitivamente no es problema de red. A que te refieres con permisos?
Pude clonar perfecto el repo template... No habrá un problema con mi repo personal? o con los repos personales en general?
