### ISSUE TITLE
Error al correr codigo

### ISSUE THREAD

**Issue by pedro-gigoux** [IIC2613-Inteligencia-Artificial-2023-1/Syllabus#80]
Hola, me esta pasando que al correr los codigos de la terminal no me está funcionando y me esta tirando errores, ¿alguna solucion para esto?

**Comment by ignaciovilla** [comment]
Hola! Que errores?

**Comment by pedro-gigoux** [comment]
Lo estoy corriendo por jupyter y me sale error al intentar descomprimir y en el pip install, te adjunto foto

![image](https://github.com/IIC2613-Inteligencia-Artificial-2023-1/Syllabus/assets/69938039/30ac76dd-fc13-4187-923e-730c68f4e7e6)
![image](https://github.com/IIC2613-Inteligencia-Artificial-2023-1/Syllabus/assets/69938039/41e5eb86-d8fe-4edd-918a-c76c7d59ff92)

el ultimo sigue harto mas el error

**Comment by pedro-gigoux** [comment]
Ya no importa, lo hice en google colab y me funciono filete

**Comment by ignaciovilla** [comment]
Eso se debe a que los comando con "!", como "!pip ..." son para colab. 
Saludos.
