### ISSUE TITLE
Error con kernel de python tras ejecución

### ISSUE THREAD

**Issue by dammr54** [IIC2613-Inteligencia-Artificial-2023-1/Syllabus#81]
Estoy trabajando de forma local y estoy teniendo problemas al ejecutar esta línea de código "face_landmarks_list = fr.face_landmarks(image)", obtengo el siguiente error:
![image](https://github.com/IIC2613-Inteligencia-Artificial-2023-1/Syllabus/assets/80791048/561f2e53-b96c-4ef3-aa37-153ffb0abcfa)
Me redirige a la siguiente pagina donde hay más información, intente solucionarlo sin éxito, 
https://github.com/microsoft/vscode-jupyter/wiki/Kernel-crashes
¿será posible que me puedan ayudar?
En cualquier caso dejare actualizado mi repositorio.

**Comment by ignaciovilla** [comment]
Hola!
Te funciona bien en colab? En ese caso puedes trabajar todo lo respectivo a la librería face recongition en colab, y generar un nuevo archivo con tus datos procesados que ya no requieren de la libería. Luego trabaja con ese archivo de forma local.
Saludos
