### ISSUE TITLE
¿Explicabilidad global con LIME?

### ISSUE THREAD

**Issue by drodrguez** [IIC2613-Inteligencia-Artificial-2023-1/Syllabus#82]
Hola, tengo una duda respecto al uso de LIME que se sugiere en el enunciado. Según tengo entendido, la librería LIME sirve para explicabilidad local, y no para explicabilidad global, que es lo que se solicita en el enunciado. ¿Puedo entonces ocupar SHAP para explicabilidad global?

**Comment by Borjampm** [comment]
Hola! Te recomendaría probar ambas cosas y compararlas, lo cual puedes incluir en tu análisis.
