### ISSUE TITLE
Tarea 3: Balance de clases

### ISSUE THREAD

**Issue by larryuc** [IIC2613-Inteligencia-Artificial-2023-1/Syllabus#85]
en la actividad 2, dice "deberán mostrar la nueva distribución de las clases y analizar el balance de estas"

Si en el análisis se detecta que está desbalanceado...
No es necesario hacer ningún tipo de balance cierto?
Esto dado que no hay un item de la tarea que lo solicite y que las técnicas son más avanzadas.

**Comment by ignaciovilla** [comment]
Hola! Puedes balancearlo o desbalancearlo según tu criterio, mientras lo justifiques y expliques bien.
Saludos!

**Comment by larryuc** [comment]
Gracias!
