### ISSUE TITLE
Duda pregunta cubos

### ISSUE THREAD

**Issue by JRichi99** [IIC2613-Inteligencia-Artificial-2023-1/Syllabus#9]
Hola buenas tardes.
Tengo una pregunta respecto a la pregunta de la tarea de los cubos.
Hay que hacer que el programa acepte crear N brazos, M cubos y  T torres?
es decir, que al correrlo entregar parametros, el programa genere sus propias condiciones iniciales, etc?

**Comment by Jairuru** [comment]
[Soy alumno] me parece que el número de torres lo determina el estado objetivo, es decir, si el estado objetivo es sobre(a,mesa,bound), sobre(b,a,bound), sobre(c,mesa,bound) y sobre(d,c,bound), entonces habrían dos torres. No estoy seguro de esto y aprovecho de comentar para cuando te respondan jeje. Saludos.

**Comment by cafigueredo** [comment]
Hola a todos,

Lo que comenta @Jairuru es correcto. No existe un numero de torres especifico, mas bien partes con una configuracion inicial (que dependiendo de cómo esten montado los bloques tendrá un numero especifico de torres) y tu objetivo es llegar a una configuracion final (que tambien cuenta con su propio numero de torres). 

No es necesario que tu programa cuente el numero de torres. Si te fijas el código base no cuenta el numero de torres, ya que no es necesario para la resolucion del problema.
